In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import sklearn
df=pd.read_csv(r'C:\Users\ATHUL AKSHAY\Desktop\Insurance\insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
df.shape

(1338, 7)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [4]:
pd.set_option('display.max_columns',None)

In [5]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df.drop('region',axis=1,inplace=True)
df.head(5)

age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [7]:
df.shape

(1338, 6)

In [8]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [9]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [10]:
df

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 62.8+ KB


In [12]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [13]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df['sex']=label_encoder.fit_transform(df['sex'])
df['smoker']=label_encoder.fit_transform(df['smoker'])

In [14]:
df

age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [15]:
df['smoker'].unique()

array([1, 0])

In [16]:
df['sex'].unique()

array([0, 1])

In [17]:
df.dtypes

age           int64
sex           int32
bmi         float64
children      int64
smoker        int32
charges     float64
dtype: object

In [18]:
df

age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [19]:
df.charges.describe()

count     1338.000000
mean     13270.422265
std      12110.011237
min       1121.873900
25%       4740.287150
50%       9382.033000
75%      16639.912515
max      63770.428010
Name: charges, dtype: float64

In [20]:
df.to_csv('insurance cleaned dataset.csv')

In [21]:
df

age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [22]:
X=df.drop(['charges'],axis=1)
y=df['charges']

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [24]:
pip install scikit_learn

Note: you may need to restart the kernel to use updated packages.


In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [26]:
X.shape

(1338, 5)

In [27]:
print(X_train.shape)

(1070, 5)


In [28]:
print(X_test.shape)

(268, 5)


In [29]:
ra=RandomForestRegressor()
ra.fit(X_train,y_train)
y_pred_randomforestregressor=ra.predict(X_test)
y_pred_randomforestregressor
# r2_score(y_test,y_pred_randomforestregressor)

array([11165.3976837 , 10316.6005492 , 44420.9107633 , 12908.770416  ,
        9553.8517711 , 10603.6481512 ,  2150.42525765, 11316.7309244 ,
        7309.072844  ,  5109.5369425 ,  7567.1245891 , 15017.7378298 ,
       10289.1318408 ,  6196.9395797 , 23945.6102164 , 12719.3567104 ,
       13224.6716871 ,  5939.6228714 ,  6365.5165965 , 33930.0771424 ,
       24002.921582  , 13110.2002804 , 11385.8381098 , 27306.920207  ,
        3644.2986913 ,  5347.212066  ,  6533.1847542 ,  8138.5662262 ,
        3736.680824  ,  9241.801326  ,  7758.0808076 , 48223.0892893 ,
       13561.2718785 , 11073.1565646 , 15756.2116893 ,  3845.4109137 ,
        8959.4156527 , 37729.6137293 , 39597.810497  ,  3854.9417994 ,
        9624.4620415 ,  3697.1098224 , 20640.7561805 , 46706.948043  ,
       36908.9931567 ,  4241.4369043 , 12762.2617784 ,  6607.221438  ,
        5013.041047  , 12534.7687246 ,  3323.367839  , 10922.917051  ,
       26083.7585997 , 49452.8108476 , 11833.09887   ,  6784.9144183 ,
      

In [30]:
ra.score(X_train,y_train)

0.9728966728291307

In [31]:
ra.score(X_test,y_test)

0.8773833813261536

In [32]:
# de=DecisionTreeRegressor()
# de.fit(X_train,y_train)
# y_pred_decisiontree=de.predict(X_test)
# r2_score(y_test,y_pred_decisiontree)

In [33]:

# lr=LinearRegression()
# lr.fit(X_train,y_train)
# y_pred_lr=lr.predict(X_test)
# r2_score(y_test,y_pred_lr)

In [34]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,explained_variance_score
from math import sqrt

In [35]:
e=explained_variance_score(y_test,y_pred_randomforestregressor)
e

0.8796544553716557

In [36]:
a=mean_absolute_error(y_test,y_pred_randomforestregressor)
a

2516.279161161473

In [37]:
a1=mean_squared_error(y_test,y_pred_randomforestregressor)
a1

19511977.90963563

In [38]:
a2=sqrt(a1)
a2

4417.236456160756

In [39]:
from sklearn import metrics
metrics.r2_score(y_test,y_pred_randomforestregressor)

0.8773833813261536

In [40]:
import pickle 
ins=open('insurance.pkl','wb')
pickle.dump(ra,ins)

In [41]:
ins1=open('insurance.pkl','rb')
forest=pickle.load(ins1)


In [42]:
forest

RandomForestRegressor()

In [43]:
prediction=forest.predict(X_test)
prediction

array([11165.3976837 , 10316.6005492 , 44420.9107633 , 12908.770416  ,
        9553.8517711 , 10603.6481512 ,  2150.42525765, 11316.7309244 ,
        7309.072844  ,  5109.5369425 ,  7567.1245891 , 15017.7378298 ,
       10289.1318408 ,  6196.9395797 , 23945.6102164 , 12719.3567104 ,
       13224.6716871 ,  5939.6228714 ,  6365.5165965 , 33930.0771424 ,
       24002.921582  , 13110.2002804 , 11385.8381098 , 27306.920207  ,
        3644.2986913 ,  5347.212066  ,  6533.1847542 ,  8138.5662262 ,
        3736.680824  ,  9241.801326  ,  7758.0808076 , 48223.0892893 ,
       13561.2718785 , 11073.1565646 , 15756.2116893 ,  3845.4109137 ,
        8959.4156527 , 37729.6137293 , 39597.810497  ,  3854.9417994 ,
        9624.4620415 ,  3697.1098224 , 20640.7561805 , 46706.948043  ,
       36908.9931567 ,  4241.4369043 , 12762.2617784 ,  6607.221438  ,
        5013.041047  , 12534.7687246 ,  3323.367839  , 10922.917051  ,
       26083.7585997 , 49452.8108476 , 11833.09887   ,  6784.9144183 ,
      